#!/bin/bash
rm -rf *.dat *.fig *.png
rm -rf POP
rm -rf COH
rm -rf CUR
rm -rf RATES
rm -rf EIGEN
rm -rf SPIN
mkdir EIGEN
mkdir SPIN
mkdir POP
mkdir COH
mkdir CUR
mkdir RATES
for i in `seq -500. 5 1500`
do
angle=$(echo "20" | bc -l)
B=$(echo "0.6" | bc -l)
gammaL=$(echo "0.0019996626067193854" | bc -l)
gammaR=$(echo "0.005" | bc -l)
pi=$(echo "3.141592653589793" | bc -l)
x=$(echo "s(($angle)*($pi)/180)*($B)" | bc -l)
y=$(echo "0." | bc -l)
z=$(echo "c(($angle)*($pi)/180)*($B)" | bc -l)
muL=$(echo "$i" | bc -l)
muR=$(echo "0" | bc -l)
cat >Floquet.input <<@
*****************************************************************
************* Please keep this FORMAT ***************************
*****************************************************************
2 ! Maximum Floquet index, number of Floquets: NF = 2*NCF +1
12 !(GHz)  Initial driving frequency f
22 !(GHz)  Final driving frequency f
20001 ! number of points in frequency swept
---------------electrode set-up-----------------------------------
$gammaR ! in meV : gamma_R_0 = 2*pi*W_R_0*W_R_0*rho
$gammaL ! in meV : gamma_L_0 = 2*pi*W_L_0*W_L_0*rho
(0.,0.) !real and imag A_R = gamma_R_1/gamma_R_0
(0.5,0.) ! real and imag A_L = gamma_L_1/gamma_L_0
0 ! phase shift rad - azimuthal angle in the bloch sphere
1 ! it multiplies the 2nd harmonic
5000 ! Cutoff (meV) for integral in Lambshift
(5,5)   ! Broadening of Green's function (meV)
1000000 ! Number of points in I11 and I21 (see Manual)
300 ! Width of the gaussian of the PDOS (meV)
0 ! >0 uses the gaussian PDOS with gau as max value, 0 a square PDOS
1 ! set number of orbital, 1 will not use any Diego Lehman coeff
.false.  ! feedbackon .true. moving tip to have Iset
1 ! target current in pA if feedbackon is true
0.001  ! tolerance in pA for reaching Iset
10  ! ratio between gammas
---------------bias, temperature, spin polarization---------------
0 ! 0 EF closer to muR if gR>>gL, 1 EF to muL, 2 Ef at mu with gamma>>
$muR  ! in mV right electrode bias
$muL ! in mV left electrode bias
0.5   ! Temperature in Kelvin
0.   ! Spin polarization of electrode R, between -1 and 1
0.5   ! Spin polarization of electrode L, between -1 and 1
0    ! 0 is left and 1 is right electrode
.true. !  .true. will compute the rates once (frequency small in rates)
---------------output file names----------------------------------
.true. ! .true. to write the populations
.true. ! .true. to write the populations and coherences
.true. ! .true. to write the spin components per site
---------------READ previous RUNS: DANGEROUS----------------------------------
.true. !if .true. reduce states to open plus a few closed channels
4 !new dimension
@
cat >H_QD.input <<@@
**********************************************************
************* Please keep this FORMAT ********************
**********************************************************
1  !Number of spins (molecules or sites)
---- Spin properties: as many blocs as Number of Spins ---
0.5 ! First spin has to be 0.5 for Transport!
0 0 0 0 ! Stephen Coefficients: B20 B22 B40 B44
0 0 1 ! Axis for Stephen Operators
$x $y $z ! Local magnetic field in Teslas
2. 2. 2. ! Local gyromagnetic factors
-----------  End of spin properties ----------------------
0  !Number of exchange connected pairs
-----------  End of exchange interactions ----------------
-359 ! eps_QD  electronic level in meV
1703  ! Hubbard U (meV)
-----------  End of electronic interactions --------------
Hamiltonian.output ! Name of the output file with H
20 ! Number of states to print in Spin_distribution.dat
**********************************************************
************* END of INPUT FILE H_QD.input ***************
**********************************************************
@@
time Floquet_ESR_v7.4.0.out
cp POPULATIONS_0.dat POPULATIONS_0_$i.dat
cp COHERENCES_n1.dat COHERENCES_n1_$i.dat
cp Current_0.dat Current_0_$i.dat
cp rates_floquet0.dat rates_floquet0_$i.dat
cp SpinFloquet_0.dat SpinFloquet_0_$i.dat
cp SpinFloquet_1.dat SpinFloquet_1_$i.dat
done
mv SpinF* SPIN
mv POPU* POP
mv COHE* COH
mv Curr* CUR
mv rates_floquet0* RATES
