#!/bin/bash
rm -rf *.dat
rm -rf POP
rm -rf COH
rm -rf CUR
rm -rf RATES
mkdir POP
mkdir COH
mkdir CUR
mkdir RATES
for  j in `seq 40 0.025 200`
do
cat >Floquet.input <<@
*****************************************************************
************* Please keep this FORMAT ***************************
*****************************************************************
2 ! Maximum Floquet index, number of Floquets: NF = 2*NCF +1
16.5 !(GHz)  Initial driving frequency f
20 !(GHz)  Final driving frequency f
6001 ! number of points in frequency swept
---------------electrode set-up-----------------------------------
0.1 ! in meV : gamma_R_0 = 2*pi*W_R_0*W_R_0*rho
0.01 ! in meV : gamma_L_0 = 2*pi*W_L_0*W_L_0*rho
0. ! A_R = gamma_R_1/gamma_R_0
0.5 ! A_L = gamma_L_1/gamma_L_0
0. ! phase shift rad - azimuthal angle in the bloch sphere
400 ! Cutoff (meV) for integral in Lambshift
.25 ! Broadening of Green's function (meV)
1000000 ! Number of points in I11 and I21 (see Manual)
100 ! Width of the gaussian of the PDOS (meV)
2 ! >0 uses the gaussian PDOS with gau as max value, 0 a square PDOS
1 ! set number of orbital, 1 will not use any Diego Lehman coeff
---------------bias, temperature, spin polarization---------------
-200  ! in mV right electrode bias
-$j ! in mV left electrode bias
0.5   ! Temperature in Kelvin
0.   ! Spin polarization of electrode R, between -1 and 1
0.45   ! Spin polarization of electrode L, between -1 and 1
0    ! 0 is left and 1 is right electrode
.true. !  .true. will compute the rates once (frequency small in rates)
---------------output file names----------------------------------
.true. ! .true. to write the populations
.true. ! .true. to write the populations and coherences
---------------READ previous RUNS: DANGEROUS----------------------------------
.true. !if .true. reduce states to open plus a few closed channels
6 !new dimension
@
cat >H_QD.input <<@@
**********************************************************
************* Please keep this FORMAT ********************
**********************************************************
2  !Number of spins (molecules or sites)
---- Spin properties: as many blocs as Number of Spins ---
0.5 ! First spin has to be 0.5 for Transport!
0 0 0 0 ! Stephen Coefficients: B20 B22 B40 B44
0 0 1 ! Axis for Stephen Operators
0.1 0 0.6 ! Local magnetic field in Teslas
2. 2. 2. ! Local gyromagnetic factors
----------------------------------------------------------
0.5 ! Second spin
0 0 0 0 ! Stephen Coefficients: B20 B22 B40 B44
0 0 1 ! Axis for Stephen Operators
0.1 0 0.6 ! Local magnetic field in Teslas
2. 2. 2. ! Local gyromagnetic factors
-----------  End of spin properties ----------------------
1  !Number of exchange connected pairs
1 2 ! Connected pairs
-10000 -10000 -10000 ! Jx Jy Jz in GHz
-----------  End of exchange interactions ----------------
-800. ! eps_QD  electronic level in meV
750  ! Hubbard U (meV)
-----------  End of electronic interactions --------------
Hamiltonian.output ! Name of the output file with H
20 ! Number of states to print in Spin_distribution.dat
**********************************************************
************* END of INPUT FILE H_QD.input ***************
**********************************************************
@@
echo "Voltage (mV)::" $j
time Floquet_ESR_v2.2.1.out
cp POPULATIONS_0.dat POPULATIONS_0_$j.dat
cp COHERENCES_1.dat COHERENCES_1_$j.dat
cp Current_0.dat Current_0_$j.dat
cp rates_floquet0.dat rates_floquet0_$j.dat
mv POPU* POP
mv COHE* COH
mv Curr* CUR
mv rates_floquet0* RATES
done
